apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-pod
  labels:
    app: css-temp
    env: dev
  namespace: dev-namespace
  annotations:
    myrepo: giving-repo
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
      name: pod-level
      
      
    spec:
      containers:
        - name: css-image
          image: gandru/villagehtml:village-app
          ports:
            - containerPort: 8080
              port: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /parvathi
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - echo hi
            initialDelaySeconds: 2
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 2
          
          
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 200m
              memory: 400Mi
