apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-pod
  labels:
    app: css-temp
  namespace: dev-namespace
  annotations:
    myrepo: giving-repo
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
        - name: css-image
          image: 
          ports:
            - containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 80         
            # initialDelaySeconds: 10
            # periodSeconds: 2
            # successThreshold: 1
            # failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /
              port: 80
            # tcpSocket:
            #   port: 80           
            # initialDelaySeconds: 2
            # periodSeconds: 6
            # successThreshold: 1
            # failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - echo
                - hi
            # initialDelaySeconds: 2
            # periodSeconds: 6
            # successThreshold: 1
            # failureThreshold: 2
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 500m
              memory: 1400Mi
